{% set name = "featurewiz" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/featurewiz-{{ version }}.tar.gz
  sha256: b74bd71b45f950fb2ffdab8ea3cfbbc585fd0f6fef80c57f928df8e4ca0eda45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7, <3.11
  run:
    - python
    - ipython
    - jupyter
    - xgboost >=1.5.1
    - pandas >=1.3.4
    - matplotlib-base
    - seaborn
    - scikit-learn >=0.24
    - networkx >=2.6.2
    - category_encoders >=2.4.0
    - xlrd >=2.0.0
    - imbalanced-learn >=0.7
    - tqdm >=4.62.0
    - dask-core >=2021.11.0
    - lightgbm >=3.2.1
    - distributed >=2021.11.0
    - feather-format >=0.4.1
    - pyarrow >=7.0.0,<7.1.dev0
    - fsspec >=0.3.3
    - pillow >=9.0.0

test:
  imports:
    - featurewiz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AutoViML/featurewiz
  summary: Select Best Features from your data set - any size - now with XGBoost!
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arturdaraujo
