{% set name = "featurewiz" %}
{% set version = "0.1.92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/featurewiz-{{ version }}.tar.gz
  sha256: 86ea12944225d92120edf1982268dd51c891ff8901590fb5abeb1a12d693db20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python
    - ipython
    - jupyter
    - xgboost >=1.5.1
    - pandas >=1.3.4
    - matplotlib-base
    - seaborn
    - scikit-learn >=0.24,<1.dev0
    - networkx >=2.8.1
    - category_encoders >=2.4.0
    - xlrd >=2.0.0
    - imbalanced-learn >=0.7
    - tqdm >=4.62.0
    - dask-core >=2021.11.0
    - lightgbm >=3.2.1
    - distributed >=2021.11.0
    - feather-format >=0.4.1
    - pyarrow ==7.0.0
    - fsspec >=0.3.3
    - imbalanced-ensemble >=0.1.7
    - pillow >=9.0.0,<9.1.dev0

test:
  imports:
    - featurewiz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AutoViML/featurewiz
  summary: Select Best Features from your data set - any size - now with XGBoost!
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arturdaraujo
